@baseUrl = http://localhost:5000

### 
# Criar prova de acesso para CPF
# @name create_CPF_access_proof
GET {{baseUrl}}/createProve/cpfAcessProof/123456789

## 
# Verificar prova de acesso para CPF
# necessario fazer o deploy na zk_verify antes  - TO DO 
# @name verify_CPF_access_proof
# GET /VerifyProof/cpfAcessProof/123456789  

### 
# Consultar credencial associada ao endereço da carteira
# Substitua {wallet_address} pelo endereço real da carteira
# Busca a prova registrada no smart contract para aquele endereço de carteira
# @name consult_CPF_access_proof
GET {{baseUrl}}/Consult/cpf/0xcF1463A5E07920B8e62Ded14FFFAeF5Bf51D9ca1

###
