driver_category = ["1", "4"]
required_letter = "4"



## Enum de categorias de habilitação:
## A = 1 => Motocicletas
## B = 2 => Automóveis
## C = 3 => Veículos de carga
## D = 4 => Veículos de transporte coletivo
## E = 5 => Veículos pesados
